---
# tasks file for k8s
# Cofiguration for k8s cluster, common to all nodes

- name: Install k8s repository
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: 0644
    owner: root
    group: root

- name: Install k8s pre-requisite packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ k8s_packages }}"

- name: Rebooting the nodes
  shell: sleep 2 && shutdown -r now "Ansible configuration triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: Waiting for nodes to come back
  wait_for:
    port: 22
    host: "{{ inventory_hostname }}"
    state: started
    delay: 10
    timeout: 200
  delegate_to: localhost
  become: false
