---
# tasks file for nodes

- name: Configure /etc/kubernetes/config
  template:
    src: k8s_config.j2
    dest: /etc/kubernetes/config
    mode: 0644
    owner: root
    group: root

- name: Configure /etc/kubernetes/kubelet
  template:
    src: kubelet.j2
    dest: /etc/kubernetes/kubelet
    mode: 0644
    owner: root
    group: root

- name: Configure /etc/sysconfig/flanneld
  template:
    src: flanneld.j2
    dest: /etc/sysconfig/flanneld
    mode: 0644
    owner: root
    group: root

- name: start services - kube-proxy kubelet flanneld docker
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - kube-proxy
    - kubelet
    - flanneld
    - docker
